//Declaring Controller as PostController
var app=angular.module('store',[]);
app.controller('RequestController',function($scope,$http){
$scope.users=true;
$scope.roles=false;
$scope.features=false;

//Method for Resetting Users Form Fields
 $scope.reset_users_data=function(){
  $scope.user_name='';
  $scope.user_designation='';
  $scope.user_department='';
  $scope.user_joined='';
  document.getElementById("users").innerHTML='';
 }
//Method for Users Form Display
$scope.users_disp=function(){
 $scope.users=true;
 $scope.roles=false;
 $scope.features=false;
}
//Method for Post Users Data  
 $scope.post_users_data=function(){
  $http({
   method:'POST',
   url:'http://localhost:8080/GitHub/ACL/Post_Users_Data.php',
   data:{'user_name':$scope.user_name,'user_designation':$scope.user_designation,'user_department':$scope.user_department,'user_joined':$scope.user_joined},
   headers:{'Content-Type':'text/plain'}
  })
  .success(function(data,status){
   console.log(data);
   console.log(status);
   document.getElementById("users").innerHTML=data;
  })
  .error(function(status){
   console.log(status);
   document.getElementById("users").innerHTML="Failed";
  })
 }
//Method for Resetting Roles Form Fields
 $scope.reset_roles_data=function(){
  $scope.role_name='';
  $scope.role_purpose='';
  document.getElementById("roles").innerHTML='';
 }
//Method for Roles Form Display
$scope.roles_disp=function(){
 $scope.users=false;
 $scope.roles=true;
 $scope.features=false;
}
//Method for Post Roles Data
 $scope.post_roles_data=function(){
  $http({
   method:'POST',
   url:'http://localhost:8080/GitHub/ACL/Post_Roles_Data.php',
   data:{'role_id':$scope.role_id,'role_name':$scope.role_name,'role_purpose':$scope.role_purpose},
   headers:{'Content-Type':'text/plain'}
  })
  .success(function(data,status){
   console.log(data);
   console.log(status);
   document.getElementById("roles").innerHTML=data;
  })
  .error(function(status){
   console.log(status);
   document.getElementById("roles").innerHTML="Failed";
  })
 }
//Method for Resetting Features Form Fields
 $scope.reset_features_data=function(){
  $scope.features_name='';
  $scope.features_descr='';
  $scope.features_perm='';
  document.getElementById("features").innerHTML='';
 }
//Method for Features Form Display
$scope.features_disp=function(){
 $scope.users=false;
 $scope.roles=false;
 $scope.features=true;
}
//Method for Post Features Data 
 $scope.post_features_data=function(){
  $http({
   method:'POST',
   url:'http://localhost:8080/GitHub/ACL/Post_Features_Data.php',
   data:{'features_name':$scope.features_name,'features_descr':$scope.features_descr,'features_perm':$scope.features_perm},
   headers:{'Content-Type':'text/plain'}
  })
  .success(function(data,status){
   console.log(data);
   console.log(status);
   document.getElementById("features").innerHTML=data;
  })
  .error(function(status){
   console.log(status);
   document.getElementById("features").innerHTML="Failed";
  })
 }
//Reset Data
 $scope.reset_feat_user=function(){
  $scope.user_name='';
  $scope.features_name='';
  $scope.role_id='';
  document.getElementById("role_features").innerHTML="";
  document.getElementById("role_user").innerHTML="";
 }
//Method for Role Features Data
 $scope.role_features_data=function(){
  $http({
   method:'POST',
   url:'http://localhost:8080/GitHub/ACL/Post_Role_Features_Data.php',
   data:{'role_id':$scope.role_id,'features_name':$scope.features_name},
   headers:{'Content-Type':'text/plain'}
  })
  .success(function(data,status){
   document.getElementById("role_features").innerHTML=data;
   console.log(data);
   console.log(status);
  })
  .error(function(status){
   document.getElementById("role_features").innerHTML="Failed";
   console.log(status);
  })
 }
//Method for Role Users data
 $scope.role_users_data=function(){
  $http({
   method:'POST',
   url:'http://localhost:8080/GitHub/ACL/Post_Role_Users_Data.php',
   data:{'role_id':$scope.role_id,'user_name':$scope.user_name},
   headers:{'Content-Type':'text/plain'}
  })
  .success(function(data,status){
   document.getElementById("role_user").innerHTML=data;
   console.log(data);
   console.log(status);
  })
  .error(function(status){
	  document.getElementById("role_user").innerHTML="Failed";
   console.log(status);
  })
 }
//Update Data
 $scope.update_data=function(){
  $http({
   method:'POST',
   url:'http://localhost:8080/GitHub/ACL/Update_Data.php',
   data:{'user_id':this.v.user_id,'user_name':this.v.user_name,'user_desg':this.v.user_designation},
   headers:{'Content-Type':'text/plain'}
  })
  .success(function(data,status){
   document.getElementById("status").innerHTML=data;
   console.log(data);
   console.log(status);
  })
  .error(function(status){
   document.getElementById("status").innerHTML="Failed";
   console.log(status);
  })
 }
//Delete Data
 $scope.delete_data=function(){
  $http({
   method:'POST',
   url:'http://localhost:8080/GitHub/ACL/Delete_Data.php',
   data:{'user_id':this.v.user_id,'user_name':this.v.user_name},
   headers:{'Content-Type':'text/plain'}
  })
  .success(function(data,status){
   document.getElementById("status").innerHTML=data;
   console.log(data);
   console.log(status);
  })
  .error(function(status){
   document.getElementById("status").innerHTML="Failed";
   console.log(status);
  })
 }
//GET Method 
 $http({
	   method:'GET',
	   url:'http://localhost:8080/GitHub/ACL/Get_Data.php',
	   headers:{'Content-Type':'text/plain'} 
	   })
 .success(function(data,status)
       {
	    $scope.get=data;
		console.log(data);
		console.log(status);
	   })
 .error(function(status,headers)
       {
	    console.log(status);
	   })
});
